### PR TITLE
Refactoring all errors in errors.go and [renamed] gocbcore/errors.go

### PR DESCRIPTION
**Pull request by ivulfson**
Need to revisit variable names, and error text.
The purpose of these changes are so that one could do this:

```
if cas, err := bucket.Upsert(key, value, 0); err != nil {
    if err == gocbcore.ErrTmpFail || err == gocbcore.ErrQueueOverflow {
        // try again later
    } else {
        // handle other errors
    }
}
```

The way current master code is implemented prevents me from doing that.

### CODE REVIEW

**Comment by brett19** [comment]
Hey Igor,

I cannot find the post that spoke about this at the moment, but the way we have the errors set up is actually intentionally designed to allow the backing structures of those errors to change around without incurring a development penalty.

Checking for specific errors is not intended to be done, instead you can look for more generic attributes, for instance:
```go
func isAuthError(err error) bool {
	te, ok := err.(interface { AuthError() bool })
	return ok && te.AuthError()
}
```

Cheers, Brett

**Comment by ivulfson** [comment]
Oh I see.  I didn't see that in the documentation.  Although I did see similar code in how net/http does errors.  Let me try that with my code, and see if that works out.  Although admittedly, `err == gocbcore.ErrQueueOverflow` is easier on the eyes`. :)

**Comment by ivulfson** [comment]
Oh, and `AuthError` isn't exported, so I can't use it in third-party code.

**Comment by brett19** [comment]
Hey Igor,

Thats the whole point of this error methodology.  You don't need anything except for the core `error` type to be able to deal with these kinds of errors!

If you look at the code above again, you will see that the AuthError that you are seeing is actually a function in an interface that we are casting to, not an type.  You can use that IsAuthClient code from anywhere! :)

Cheers, Brett

**Comment by ivulfson** [comment]
Right, sorry, I do see that it's exported.  I'll need to go pound at the keyboard some more. :)  Thanks for your attention, I'll keep you posted.

**Comment by brett19** [comment]
Sounds good.  I'll leave this PR open for now for the discussion to continue, please close it if you resolve your issue and are happy!

Cheers, Brett

**Comment by ivulfson** [comment]
OK, so looks like this prama is working, but I do need more methods. :)  I am getting gocbcore.overloadError{} error, and I'm not sure how to test if that's what I'm getting.  Any ideas?

**Comment by ivulfson** [comment]
Adding this to gocbcore/error.go helps:

```
func (e generalError) GeneralError() bool {
       return true
}
func (e overloadError) OverloadError() bool {
       return true
}
func (e agentError) AgentError() bool {
       return true
}
```

Also, some of the codes covered in `memdError()` aren't covered by a method: `StatusNotStored`, `StatusTooBig`, and a few others.

**Comment by brett19** [comment]
Hey Igor!

There are indeed some gaps in the exposed methods!  Please let me know if you find any others!
I've created a ticket mentioning this ticket to resolve the gaps that I'm aware of here: https://issues.couchbase.com/browse/GOCBC-26.

Cheers, Brett

**Comment by ivulfson** [comment]
I commended on the Jira you mentioned.

Some errors are missing interfaces that would allow one to do something like this:

```
func isAuthError(err error) bool {
    te, ok := err.(interface { AuthError() bool })
    return ok && te.AuthError()
}
```

The errors that are missing interfaces are:

gocb:

`clientError`

gocbcore:

```
generalError
overloadError
agentError
```

Additionally, in gocbcore, some status codes in memdError aren't available via interface.  These status codes are:

```
StatusTooBig
StatusNotStored
StatusBadDelta
StatusNotMyVBucket
StatusAuthContinue
StatusUnknownCommand
*unknown error code as default clause in memdError.Error() function
```

**Comment by ivulfson** [comment]
Feel free to close this pull request, and I'm going to drop my branch.

**Comment by TrollWarlord** [comment]
I'm lost, because of the error do you do... error.AuthError() ? I can't see how you either pass it in or.. reference it.

They also don't show up on godoc with this pattern

**Comment by ivulfson** [comment]
Brett told you exactly how to do it:

```
func isAuthError(err error) bool {
    te, ok := err.(interface { AuthError() bool })
    return ok && te.AuthError()
}
```

The above asserts the provided `err` to an interface that implements AuthError() function, which returns a bool.  If that assertion was successful, and if the result of call to `AuthError()` was true, then it's an authentication error.  The beauty and weirdness of Go interface, in action.

and

```
bucket, err := cluster.OpenBucket(config.Bucket, config.Password)
if err != nil {
    if isAuthError(err) {
         // handle authentication error
    }
}
```

**Comment by TrollWarlord** [comment]
So.. we have to copy this out? It's not exported? I'm kinda lost lol feels weird... I like the ErrAuth

**Comment by ivulfson** [comment]
Yeah, you have to implement it in your code.  I'm writing a wrapper around gocb, just like I did for perl-Couchbase - too much work is left as an excersise to the reader.

**Comment by mschoch** [comment]
Feels to me like its just trying to be too clever.  Why doesn't the library just define these as actual interfaces so the caller can check them in one line like:

	if _, ok := err.(AuthError); ok {
		// dead with auth error
	}

Is there some other source using/advocating this pattern?

**Comment by ivulfson** [comment]
That would be nice, that's all I got to say.  Feels like error handling hasn't been worked out just yet.  Lack of godoc points to the same fact.

**Comment by brett19** [comment]
Hey guys,

The reason for the particular method of handling errors right now is it allows a lot of flexibility in terms of passing errors from the internal gocbcore library straight through without any additional marshalling.  It is also beneficial to external libraries wrapping gocb for the same reasons.

P.S. I'm still very open to changing how the error handling works, we are still in pre-beta development on the library, so please suggest alternatives and hopefully we can have a productive discussion and land someplace awesome.

Cheers, Brett

**Comment by ivulfson** [comment]
Well, whatever solution, I just hope it's a complete one.  Right now I can't even test for `overloadError`, in heavily multi-threaded (multi-goroutined?) environment.

**Pull request closed without merging**
